service: rock-paper-scissors

custom:
  config: ${file(src/config/index.js):asFunction}

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    NODE_ENV: ${opt:stage}

functions:
  alexa:
    timeout: 6
    handler: src/handler.alexaHandler
    memorySize: 512
    events:
      - alexaSkill: ${env:SKILL_ID}

package:
  excludeDevDependencies: true
  include:
    - src/config/*.json

  exclude:
    - scripts/**
    - assets/**
    - reports/**
    - speech-assets/**

resources:
  Resources:
    assets:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.config.s3.bucket}
        AccessControl: PublicRead
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - "*"
              AllowedMethods:
                - GET
